version: '3'

services:
  bot:
    container_name: deepzBOT
    restart: always
    links:
      - "mongo"
    build: .
    volumes:
      - ./dist:/usr/src/app/dist
      - ./.env.production:/usr/src/app/.env

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: DiscordBOT
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: